// Generated by CoffeeScript 1.10.0
(function() {
  var Main;

  window.Main = Main = (function() {
    function Main() {
      this.getUsersDataOnPageLoad();
    }

    Main.prototype.init = function() {
      return $("body").on("click", "#submitInput", function(e) {
        var inputData, inputText;
        inputText = $("#inputTextArea").val();
        return inputData = $.csv.toObjects(inputText);
      });
    };

    Main.prototype.getUsersDataOnPageLoad = function() {
      return $.ajax({
        type: "GET",
        async: false,
        url: "data/sample.csv",
        dataType: "text",
        success: (function(_this) {
          return function(csvdata) {
            var data, html;
            data = $.csv.toObjects(csvdata);
            html = _this.generateTable(data);
            return $("#locationTable").html(html);
          };
        })(this)
      });
    };

    Main.prototype.generateTable = function(data) {
      var keysAr, requiredHtml;
      requiredHtml = "";
      if (typeof data[0] === 'undefined') {
        return null;
      }
      keysAr = Object.keys(data[0]);
      requiredHtml += this.gettingHeader(keysAr);
      requiredHtml += this.gettingRows(data);
      return requiredHtml;
    };

    Main.prototype.gettingHeader = function(keysAr) {
      var html, item;
      html = "";
      html += "<thead><tr>\r\n";
      for (item in keysAr) {
        html += "<td>" + keysAr[item] + "</td>\r\n";
      }
      html += "<td>Active/Inactive</td>";
      html += "</tr></thead>\r\n";
      return html;
    };

    Main.prototype.gettingRows = function(data) {
      var html, i, val, values;
      html = "";
      html += "<tbody>";
      i = 0;
      while (i <= data.length - 1) {
        values = Object.values(data[i]);
        html = html + '<tr>\u000d\n';
        for (val in values) {
          html += '<td>' + values[val] + '</td>\u000d\n';
        }
        html += '<td><input type=\'checkbox\' id=\'' + values[0] + '\'></td>';
        html += '</tr>\u000d\n';
        i++;
      }
      html += "</tbody>";
      return html;
    };

    return Main;

  })();

}).call(this);
