// Generated by CoffeeScript 1.10.0
(function() {
  var Main,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Main = Main = (function() {
    function Main() {
      this.initializeMap = bind(this.initializeMap, this);
      this.spotPredefinedData = bind(this.spotPredefinedData, this);
      this.allDataFromCSV = this.getCSVStoredDataArray();
      this.spotPredefinedData();
    }

    Main.prototype.init = function() {
      return $("body").on("click", "#submitInput", (function(_this) {
        return function(e) {
          var html, inputData, inputText;
          inputText = $("#inputTextArea").val();
          inputData = $.csv.toObjects(inputText);
          html = _this.generateTable(inputData);
          return $("#locationTable").html(html);
        };
      })(this));
    };

    Main.prototype.getCSVStoredDataArray = function() {
      var dataArray;
      dataArray = [];
      $.ajax({
        type: "GET",
        async: false,
        url: "data/sample.csv",
        dataType: "text",
        success: (function(_this) {
          return function(csvdata) {
            return dataArray = $.csv.toObjects(csvdata);
          };
        })(this)
      });
      return dataArray;
    };

    Main.prototype.getUsersDataOnPageLoad = function() {
      var dataArray, html;
      dataArray = this.getCSVStoredDataArray();
      html = this.generateTable(dataArray);
      return $("#locationTable").html(html);
    };

    Main.prototype.generateTable = function(data) {
      var keysAr, requiredHtml;
      requiredHtml = "";
      if (typeof data[0] === 'undefined') {
        return null;
      }
      keysAr = Object.keys(data[0]);
      requiredHtml += this.gettingHeader(keysAr);
      requiredHtml += this.gettingRows(data);
      return requiredHtml;
    };

    Main.prototype.gettingHeader = function(keysAr) {
      var html, item;
      html = "";
      html += "<thead><tr>\r\n";
      for (item in keysAr) {
        html += "<td>" + keysAr[item] + "</td>\r\n";
      }
      html += "<td>Active/Inactive</td>";
      html += "</tr></thead>\r\n";
      return html;
    };

    Main.prototype.gettingRows = function(data) {
      var html, i, val, values;
      html = "";
      html += "<tbody>";
      i = 0;
      while (i <= data.length - 1) {
        values = Object.values(data[i]);
        html = html + '<tr>\u000d\n';
        for (val in values) {
          html += '<td>' + values[val] + '</td>\u000d\n';
        }
        html += '<td><input type=\'checkbox\' id=\'' + values[0] + '\'></td>';
        html += '</tr>\u000d\n';
        i++;
      }
      html += "</tbody>";
      return html;
    };

    Main.prototype.getGeoLocations = function() {
      var valuesAr;
      valuesAr = [];
      $.each(this.allDataFromCSV, (function(_this) {
        return function(i, row) {
          var values;
          values = {
            "lat": row["Garage Latitude"],
            "lng": row["Garage Longitude"]
          };
          return valuesAr.push(values);
        };
      })(this));
      return valuesAr;
    };

    Main.prototype.spotPredefinedData = function() {
      return google.maps.event.addDomListener(window, 'load', this.initializeMap);
    };

    Main.prototype.initializeMap = function() {
      var infoWindow, map, mapProp, position;
      infoWindow = this.getGeoLocations()[0];
      position = new google.maps.LatLng(infoWindow.lat, infoWindow.lng);
      mapProp = {
        center: position,
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
      $.each(this.getGeoLocations(), function(i, location) {
        var marker;
        marker = new google.maps.Marker({
          position: new google.maps.LatLng(location.lat, location.lng)
        });
        return marker.setMap(map);
      });
    };

    return Main;

  })();

}).call(this);
